name: Start Runner
  
on:
  workflow_call:
    outputs:
      runner:
        description: "The runner output string"
        value: ${{ jobs.startrunner.outputs.runner }}
      
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.readid.outputs.runner }}
      runnerflag: ${{ steps.readid.outputs.flag }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::883965538462:role/testrole
          aws-region: us-east-1
      - name: test
        id: readid
        run: |
           aws s3 ls
           
