name: Start/stop AWS EC2
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
                   
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: |
          aws ec2 stop-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID_2 }}
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID1 }}
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID3 }}
  
