name: Build
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:

  Pre-Release:
    name: Pre-Release
    uses: ./.github/workflows/pre-release.yml
    
  initializerunner:
    name: Intialize Runner
    needs: Pre-Release
    uses: ./.github/workflows/action.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      
  build:
     needs: [initializerunner,Pre-Release]
     runs-on: ${{ needs.initializerunner.outputs.activerunner }}
     steps:
      - uses: actions/checkout@v2
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: '11'
#           distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean verify 
#       - name: Deploy to Github Package Registry
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#            mvn deploy:deploy-file -Dfile=./target/Example-0.0.1.war -DpomFile=./pom.xml -Dinternal.repo.id=github -Dinternal.repo.username=2115-27 -Dinternal.repo.password=Athulya@2115 -Durl=https://maven.pkg.github.com/2115-27/java-maven-sample-war -Dtoken=GITHUB_TOKEN
                           
  Sonar:
    needs: [build,initializerunner]
    runs-on: ${{ needs.initializerunner.outputs.activerunner }}
    steps: 
      - uses: actions/checkout@v2
      - name: Sonar Analysis
        
        run: |
          echo Sonar Starts here!!
          mvn -B verify sonar:sonar -Dsonar.projectKey=2115-27_java-maven-sample-war -Dsonar.organization=2115-27 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  Fortify:
    needs: [initializerunner,Pre-Release]
    runs-on: ubuntu-latest
    steps:    
      - name: Fortify Analysis
        run: echo Starting Fortify stage!!
        
  Post-Release:
    name: Post-Release
    needs: [initializerunner,Pre-Release,build,Sonar,Fortify]
    uses: ./.github/workflows/post-release.yml  
      
  Declarative-Post-Actions:
    needs: [Post-Release]
    runs-on: ubuntu-latest
    steps:    
      - name: Sent Results
        run: echo Mailing results to recipients!!     
        
  stop_runner:
    needs: [initializerunner,build,Sonar,Declarative-Post-Actions]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.initializerunner.outputs.activerunner }}
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.activerunner }} --region us-west-1
