name: Build
on: 
  workflow_dispatch:
  
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}          
jobs:
  initializerunner:
    name: Intialize Runner
    uses: ./.github/workflows/action.yml
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}
             
  build:
       needs: initializerunner
       runs-on: ${{ needs.initializerunner.outputs.activerunner }}
       steps:
          - run: |
             echo "Hello World"
             sleep 240
           
  stop_runner:
    needs: [ build, initializerunner]
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.activerunner }} --region us-west-2
