name: Build
on: 
  workflow_dispatch:
  
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#     GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
    
jobs:
  initializerunner:
    name: Intialize Runner
    uses: ./.github/workflows/action.yml
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
             
  BuildandAnalyze:
       needs: initializerunner
       runs-on: ${{ needs.initializerunner.outputs.activerunner }}
       steps:
          - run: |
             echo "Hello World"
             sleep 60
             mvn -B verify sonar:sonar -Dsonar.projectKey=shiyamsundark_java-maven-sample-war -Dsonar.organization=shiyamsundark -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
             
  
  stop_runner:
    needs: [ BuildandAnalyze, initializerunner]
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.activerunner }} --region us-west-2
