# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on: 
  workflow_dispatch:

jobs:
  startawsec2:
    runs-on: ubuntu-latest
    steps:
      - name: startec2
        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }} 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  sleep-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: waiting ec2 to start
        run: |
          sleep 60
  stopawsec2:
    runs-on: ubuntu-latest
    steps:
      - name: stopec2
        run: |
          aws ec2 stop-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
          output:
          {
            "StoppingInstances": [
          {
             "InstanceId": "i-1234567890abcdef0",
             "CurrentState": {
                 "Code": 64,
                 "Name": "stopping"
             },
             "PreviousState": {
                 "Code": 16,
                 "Name": "running"
                  }
                }
             ]
          }
   
           
  
      
  
    
