name: Build
on: 
  workflow_dispatch:
          
jobs:
  initializerunner:
    name: Intialize Runner
    uses: shiyamsundark/java-maven-sample-war/.github/workflows/action.yml@testm
    secrets: 
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}
       AWS_DEFAULT_REGION: "us-west-2"
    
           
  build:
     needs: initializerunner
     runs-on: ${{ needs.initializerunner.outputs.runner }}
     steps:
        - run: |
           echo "Hello World"
           sleep 240
           
  stop_runner:
    needs: [ build, initializerunner]
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.runner }}
