name: Java CI with Maven
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
           AWS_s3_bucket: ${{ secrets.AWS_S3BUCKET_NAME }}
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.readid.outputs.runner }}
      runnerflag: ${{ steps.readid.outputs.flag }}
    steps:
      - uses: actions/checkout@v3
      - id: readid
        run: |
           aws s3 cp s3://awsinstanceid/awsinstanceid.txt ${{github.workspace}}
           ls -la ${{github.workspace}}
          
           
#   Runner-status-check:
#     needs: startrunner
#     runs-on: ubuntu-latest
#     if: ${{ needs.startrunner.outputs.flag }} == 'false'
    
    
#   build:
#      needs: startrunner
#      runs-on: self-hosted
#      steps:
#         - run: |
#            echo "Hello World"
#            sleep 180
           
#   stop_runner:
#     needs: [build, startrunner]
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           aws ec2 stop-instances --instance-ids ${{ needs.startrunner.outputs.runner }}
