name: Post-Release
on: 
  workflow_call:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
jobs:
    Post-Release:
      runs-on: ubuntu-latest
      steps:    
        - name: Post Release Task
          run: |
            echo Update Versioning Repo!!
            aws s3 cp s3://instidbucket/version/version.cfg ${{ github.workspace }}/versions.cfg --region us-west-1
            cat versions.cfg
            echo "${{ github.run_id }}" >> versions.cfg
            cat versions.cfg
          
