name: Test Build
on:
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
jobs:
  Set_Release_Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: |
          echo setting release version!!  
          cp version.cfg ${{ github.workspace }}/versions.cfg 
          echo "${{ github.run_number }}" >> versions.cfg
          newversion=$(cat versions.cfg)
          echo $newversion
          
    
     
