name: TestBuild

on:
  workflow_dispatch:

# permissions:
#   contents: write
#   packages: write
    
jobs:
  Set-Release-Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Version
        run: |
          cd java-maven-sample-war/
          echo "${{github.run_number }}" >> version.cfg
          newversion=$(cat versions.cfg)
          echo $newversion
