name: Test Build
on:
  workflow_dispatch:

jobs:
  Set_Release_Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: |
          echo setting release version!!  
          echo "${{ github.run_number }}" >> version.cfg
          newversion=$(cat version.cfg | tr -d "[:space:]")
          echo $newversion is the version
          
          
    
     
