name: Test Build
on:
  workflow_dispatch:
jobs:
  Set_Release_Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: |
          echo setting release version!!  
          aws s3 cp s3://instidbucket/version/versionnew.cfg ${{ github.workspace }}/version.cfg --region us-west-1 
          echo "${{ github.run_number }}" >> version.cfg
          newversion=$(cat version.cfg)
          echo $newversion
          
    
     
