name: .NET Build testing

on:
  workflow_dispatch:
permissions:
      contents: read
      packages: write  
jobs:
  test1:
    runs-on: ubuntu-latest
    name: test1
    steps:
       name: Hai
        run: echo "hello world"

   
